//! # entelix-tool-derive
//!
//! `#[tool]` attribute macro for typed-input tool authoring. The
//! macro takes an `async fn` whose signature is
//!
//! ```ignore
//! async fn name(ctx: &AgentContext<()>, arg1: T1, arg2: T2, ...) -> Result<O>
//! ```
//!
//! and generates everything an agent needs to dispatch it as an
//! `entelix_tools::SchemaTool`:
//!
//! 1. An `<Name>Input` struct over the argument list, derived
//!    `serde::Deserialize` + `schemars::JsonSchema`.
//! 2. A unit struct `<Name>` (`snake_case` → `PascalCase`).
//! 3. A `SchemaTool` impl that deserialises the JSON input,
//!    forwards to the original async fn, and returns the typed
//!    output.
//!
//! The original function stays callable from user code — the
//! macro **adds** items to the surrounding module, it does not
//! replace the function.
//!
//! ## Example
//!
//! ```ignore
//! use entelix_core::AgentContext;
//! use entelix_core::error::Result;
//! use entelix_tools::tool;
//!
//! #[tool]
//! /// Calculate compound interest.
//! ///
//! /// Inputs are validated against the autogenerated JSON schema.
//! async fn compound_interest(
//!     _ctx: &AgentContext<()>,
//!     principal: f64,
//!     rate: f64,
//!     years: u32,
//! ) -> Result<f64> {
//!     #[allow(clippy::cast_lossless, clippy::cast_possible_wrap)]
//!     Ok(principal * (1.0 + rate).powi(years as i32))
//! }
//!
//! // Generated: `CompoundInterest` (struct) + `CompoundInterestInput`
//! // (struct) + `SchemaTool` impl. Register via `.into_adapter()`:
//! //
//! //   ToolRegistry::new()
//! //       .register(Arc::new(CompoundInterest.into_adapter()))?;
//! ```
//!
//! ## What the macro does NOT support (1.0)
//!
//! - Generic / lifetime-parameterised functions — implement
//!   `SchemaTool` manually.
//! - Custom tool name overrides — rename the function.
//! - Effect / retry-hint annotations — implement `SchemaTool`
//!   manually until 1.x adds attribute arguments.
//! - Typed `D` (non-`()`) deps — first cut targets `Tool<()>`;
//!   typed-deps macro support lands when `ToolRegistry<D>` (slice
//!   103) settles the call shape.

#![doc(html_root_url = "https://docs.rs/entelix-tool-derive/0.4.1")]
#![deny(missing_docs)]

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::{
    Attribute, Expr, ExprLit, FnArg, GenericArgument, Ident, ItemFn, Lit, LitStr, Meta, Pat,
    PatType, PathArguments, ReturnType, Token, Type, Visibility, parse::Parse, parse::ParseStream,
    parse_macro_input, punctuated::Punctuated, spanned::Spanned,
};

/// Optional metadata captured from `#[tool(...)]` attribute args.
/// Every field is `Option` so the absence of an arg leaves the
/// generated impl on `SchemaTool`'s default accessor.
#[derive(Default)]
struct ToolArgs {
    /// Override the tool name. Defaults to the function ident as a
    /// `&'static str`. Use when the function name and the
    /// model-facing name diverge (e.g. `calc_v2` impl, `"calculator"`
    /// public name).
    name: Option<LitStr>,
    /// `ToolEffect` variant ident — `ReadOnly` / `Mutating` / etc.
    /// Captured as an [`Ident`] so the generated path is
    /// `::entelix_core::tools::ToolEffect::ReadOnly`.
    effect: Option<Ident>,
    /// Flag: `idempotent` (without value) → `fn idempotent() = true`.
    idempotent: bool,
    /// Version label, e.g. `"1.2.3"`.
    version: Option<LitStr>,
    /// `RetryHint` constructor ident — `idempotent_transport` /
    /// `non_idempotent`. The generated impl emits
    /// `Some(::entelix_core::tools::RetryHint::idempotent_transport())`.
    retry_hint: Option<Ident>,
}

impl Parse for ToolArgs {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let mut args = Self::default();
        if input.is_empty() {
            return Ok(args);
        }
        let punctuated: Punctuated<Meta, Token![,]> = Punctuated::parse_terminated(input)?;
        for meta in punctuated {
            match &meta {
                Meta::NameValue(nv) if nv.path.is_ident("name") => {
                    args.name = Some(parse_str_lit(&nv.value)?);
                }
                Meta::NameValue(nv) if nv.path.is_ident("effect") => {
                    let s = parse_str_lit(&nv.value)?;
                    args.effect = Some(Ident::new(&s.value(), s.span()));
                }
                Meta::Path(p) if p.is_ident("idempotent") => {
                    args.idempotent = true;
                }
                Meta::NameValue(nv) if nv.path.is_ident("version") => {
                    args.version = Some(parse_str_lit(&nv.value)?);
                }
                Meta::NameValue(nv) if nv.path.is_ident("retry_hint") => {
                    let s = parse_str_lit(&nv.value)?;
                    args.retry_hint = Some(Ident::new(&s.value(), s.span()));
                }
                _ => {
                    return Err(syn::Error::new(
                        meta.span(),
                        "#[tool] supports `name = \"…\"`, `effect = \"…\"`, \
                         `idempotent`, `version = \"…\"`, `retry_hint = \"…\"`",
                    ));
                }
            }
        }
        Ok(args)
    }
}

fn parse_str_lit(expr: &Expr) -> syn::Result<LitStr> {
    match expr {
        Expr::Lit(ExprLit {
            lit: Lit::Str(s), ..
        }) => Ok(s.clone()),
        _ => Err(syn::Error::new(expr.span(), "expected a string literal")),
    }
}

/// Generate an `entelix_tools::SchemaTool` impl from an async fn.
/// See the crate-level docs for the contract and an example.
#[proc_macro_attribute]
pub fn tool(attr: TokenStream, item: TokenStream) -> TokenStream {
    let args = parse_macro_input!(attr as ToolArgs);
    let input_fn = parse_macro_input!(item as ItemFn);
    expand(&input_fn, &args)
        .unwrap_or_else(syn::Error::into_compile_error)
        .into()
}

#[allow(clippy::too_many_lines)] // Expansion is a flat sequence of validation + parse + emit; splitting fragments span / hygiene continuity.
fn expand(input_fn: &ItemFn, args: &ToolArgs) -> syn::Result<TokenStream2> {
    // ── Validation ──────────────────────────────────────────────
    if input_fn.sig.asyncness.is_none() {
        return Err(syn::Error::new(
            input_fn.sig.span(),
            "#[tool] requires an `async fn`; convert the body to async or implement \
             `entelix_tools::SchemaTool` manually for sync work",
        ));
    }
    if !input_fn.sig.generics.params.is_empty() {
        return Err(syn::Error::new(
            input_fn.sig.generics.span(),
            "#[tool] does not yet support generic / lifetime-parameterised functions; \
             implement `entelix_tools::SchemaTool` manually",
        ));
    }
    if !matches!(input_fn.sig.output, ReturnType::Type(_, _)) {
        return Err(syn::Error::new(
            input_fn.sig.span(),
            "#[tool] requires `Result<O>` as the return type",
        ));
    }
    let ReturnType::Type(_, return_ty) = &input_fn.sig.output else {
        unreachable!("guarded above");
    };
    let output_ty = extract_result_ok(return_ty)?;

    // ── Parse params (split optional ctx from input fields) ─────
    //
    // Ctx detection runs on the *type*, not the parameter name —
    // `&AgentContext<…>` at index 0 is the ctx slot regardless of
    // whether the binding is `ctx`, `_ctx`, or omitted entirely
    // (`_: &AgentContext<()>`). All other parameters become
    // `Input` fields.
    let mut has_ctx = false;
    let mut input_fields: Vec<(Ident, Type)> = Vec::new();
    for (idx, arg) in input_fn.sig.inputs.iter().enumerate() {
        let FnArg::Typed(PatType { pat, ty, .. }) = arg else {
            return Err(syn::Error::new(
                arg.span(),
                "#[tool] cannot apply to a method (no `self` receiver allowed); \
                 lift the body to a free async fn",
            ));
        };
        if idx == 0 && is_agent_context_ref(ty) {
            has_ctx = true;
            continue;
        }
        let Pat::Ident(pat_ident) = pat.as_ref() else {
            return Err(syn::Error::new(
                pat.span(),
                "#[tool] requires every parameter to use a plain identifier pattern",
            ));
        };
        let name = &pat_ident.ident;
        if is_agent_context_ref(ty) {
            return Err(syn::Error::new(
                ty.span(),
                "#[tool]: `&AgentContext<…>` is the optional first argument; \
                 move it to position 0 or remove it",
            ));
        }
        input_fields.push((name.clone(), (**ty).clone()));
    }

    // ── Names + visibility ──────────────────────────────────────
    let fn_name = &input_fn.sig.ident;
    let fn_name_str = fn_name.to_string();
    let pascal = to_pascal_case(&fn_name_str);
    let struct_ident = Ident::new(&pascal, fn_name.span());
    let input_struct_ident = Ident::new(&format!("{pascal}Input"), fn_name.span());
    let vis = &input_fn.vis;
    let inner_vis = inner_field_vis(vis);

    let tool_name = args
        .name
        .as_ref()
        .map_or_else(|| fn_name_str.clone(), LitStr::value);
    let description = first_doc_paragraph(&input_fn.attrs).unwrap_or_else(|| fn_name_str.clone());

    // ── Optional metadata override accessors ────────────────────
    let effect_override = args.effect.as_ref().map(|ident| {
        quote! {
            fn effect(&self) -> ::entelix_core::tools::ToolEffect {
                ::entelix_core::tools::ToolEffect::#ident
            }
        }
    });
    let idempotent_override = if args.idempotent {
        Some(quote! {
            fn idempotent(&self) -> bool { true }
        })
    } else {
        None
    };
    let version_override = args.version.as_ref().map(|lit| {
        quote! {
            fn version(&self) -> Option<&str> { Some(#lit) }
        }
    });
    let retry_hint_override = args.retry_hint.as_ref().map(|ident| {
        quote! {
            fn retry_hint(&self) -> Option<::entelix_core::tools::RetryHint> {
                Some(::entelix_core::tools::RetryHint::#ident())
            }
        }
    });

    // ── Generated `Input` struct ────────────────────────────────
    let input_field_decls = input_fields.iter().map(|(name, ty)| {
        quote! { #inner_vis #name: #ty, }
    });
    let input_doc = format!("Typed input for the [`{struct_ident}`] tool.");
    let input_struct = quote! {
        #[doc = #input_doc]
        #[allow(missing_docs)] // Per-field docs come from the source fn's parameter list,
                               // which the macro does not yet propagate; field names map
                               // 1:1 to the original async fn args.
        #[derive(::serde::Deserialize, ::schemars::JsonSchema)]
        #vis struct #input_struct_ident {
            #(#input_field_decls)*
        }
    };

    // ── Generated unit struct ───────────────────────────────────
    let unit_doc = format!(
        "`{tool_name}` tool — generated from `{fn_name_str}` by `#[tool]`. \
         Register via [`SchemaToolExt::into_adapter`].\n\n{description}"
    );
    let unit_struct = quote! {
        #[doc = #unit_doc]
        #[derive(Debug, Default, Clone, Copy)]
        #vis struct #struct_ident;
    };

    // ── Generated SchemaTool impl ───────────────────────────────
    let arg_idents: Vec<&Ident> = input_fields.iter().map(|(name, _)| name).collect();
    let dispatch = if has_ctx {
        quote! { #fn_name(__ctx, #(__input.#arg_idents,)*).await }
    } else {
        quote! { #fn_name(#(__input.#arg_idents,)*).await }
    };

    let schema_impl = quote! {
        #[::async_trait::async_trait]
        impl ::entelix_tools::SchemaTool for #struct_ident {
            type Input = #input_struct_ident;
            type Output = #output_ty;
            const NAME: &'static str = #tool_name;

            fn description(&self) -> &str {
                #description
            }

            #effect_override
            #idempotent_override
            #version_override
            #retry_hint_override

            async fn execute(
                &self,
                __input: Self::Input,
                __ctx: &::entelix_core::AgentContext<()>,
            ) -> ::entelix_core::error::Result<Self::Output> {
                #dispatch
            }
        }
    };

    Ok(quote! {
        #input_fn

        #input_struct

        #unit_struct

        #schema_impl
    })
}

/// Detect `&AgentContext<…>` at any nesting depth of references —
/// `&AgentContext<()>`, `&'a AgentContext<MyDeps>`, etc. all match.
/// The macro treats this as the ctx slot when it appears at the
/// first parameter position.
fn is_agent_context_ref(ty: &Type) -> bool {
    let Type::Reference(reference) = ty else {
        return false;
    };
    let Type::Path(type_path) = reference.elem.as_ref() else {
        return false;
    };
    type_path
        .path
        .segments
        .last()
        .is_some_and(|seg| seg.ident == "AgentContext")
}

/// Extract `O` from `Result<O>` (any path ending in
/// `Result<…>` with at least one type argument). Operators
/// using a custom alias whose canonical form is `Result<…>`
/// — e.g. `entelix_core::error::Result<O>` aliasing
/// `std::result::Result<O, Error>` — pass through.
fn extract_result_ok(ty: &Type) -> syn::Result<Type> {
    let Type::Path(type_path) = ty else {
        return Err(syn::Error::new(
            ty.span(),
            "#[tool] return type must be `Result<O>`",
        ));
    };
    let Some(last) = type_path.path.segments.last() else {
        return Err(syn::Error::new(
            ty.span(),
            "#[tool] return type path is empty",
        ));
    };
    if last.ident != "Result" {
        return Err(syn::Error::new(
            last.ident.span(),
            "#[tool] requires the return type to end in `Result<…>`",
        ));
    }
    let PathArguments::AngleBracketed(generics) = &last.arguments else {
        return Err(syn::Error::new(
            last.arguments.span(),
            "#[tool] requires `Result<O>` with an explicit type argument",
        ));
    };
    let Some(GenericArgument::Type(ok_ty)) = generics.args.first() else {
        return Err(syn::Error::new(
            generics.args.span(),
            "#[tool] requires `Result<O>` whose first generic is the `Ok` type",
        ));
    };
    Ok(ok_ty.clone())
}

/// Derive the trimmed first-paragraph block of consecutive
/// `#[doc = "..."]` attributes; every line up to the first blank
/// `#[doc = ""]` is treated as the description, joined with single
/// spaces. Returns `None` when no doc comment was present.
fn first_doc_paragraph(attrs: &[Attribute]) -> Option<String> {
    let mut lines: Vec<String> = Vec::new();
    for attr in attrs {
        let Meta::NameValue(nv) = &attr.meta else {
            continue;
        };
        if !nv.path.is_ident("doc") {
            continue;
        }
        let Expr::Lit(ExprLit {
            lit: Lit::Str(s), ..
        }) = &nv.value
        else {
            continue;
        };
        let raw = s.value();
        let trimmed = raw.trim();
        if trimmed.is_empty() {
            // First blank line ends the description paragraph.
            if !lines.is_empty() {
                break;
            }
            continue;
        }
        lines.push(trimmed.to_owned());
    }
    if lines.is_empty() {
        None
    } else {
        Some(lines.join(" "))
    }
}

/// Convert `snake_case_ident` → `PascalCaseIdent`.
fn to_pascal_case(snake: &str) -> String {
    let mut out = String::with_capacity(snake.len());
    let mut upper_next = true;
    for ch in snake.chars() {
        if ch == '_' {
            upper_next = true;
            continue;
        }
        if upper_next {
            out.extend(ch.to_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

/// Field visibility for the generated `Input` struct mirrors the
/// outer struct's visibility — public functions surface public
/// fields so `let input = MyToolInput { … }` compiles in operator
/// code, private functions stay private.
fn inner_field_vis(outer: &Visibility) -> TokenStream2 {
    match outer {
        Visibility::Public(_) => quote! { pub },
        Visibility::Restricted(restricted) => {
            let path = &restricted.path;
            let in_token = restricted.in_token;
            quote! { pub(#in_token #path) }
        }
        Visibility::Inherited => quote! {},
    }
}
