//! End-to-end exercise of `#[tool]`: declare a typed-input async
//! fn, register the generated tool through a `ToolRegistry`,
//! dispatch a JSON-valued call, assert the typed output.

// `#[tool]` requires `async fn`; minimal test bodies have no
// `.await` but stay async to exercise the macro contract.
#![allow(clippy::unwrap_used, clippy::indexing_slicing, clippy::unused_async)]

use std::sync::Arc;

use entelix_core::AgentContext;
use entelix_core::context::ExecutionContext;
use entelix_core::error::Result;
use entelix_core::tools::ToolRegistry;
use entelix_tool_derive::tool;
use entelix_tools::SchemaToolExt;
use serde_json::json;

#[tool]
/// Echo the message back verbatim.
///
/// Trailing paragraphs of the doc comment are not surfaced to
/// the model — they stay inline as developer documentation.
async fn echo(_ctx: &AgentContext<()>, message: String) -> Result<String> {
    Ok(message)
}

#[tool]
/// Sum two integers.
async fn add(_ctx: &AgentContext<()>, a: i64, b: i64) -> Result<i64> {
    Ok(a + b)
}

/// Tool with no `ctx` parameter — the macro accepts the
/// ctx-less shape for tools that do not consult the request
/// context (cancellation, tenant, deps, audit sink).
#[tool]
/// Negate an integer.
async fn negate(value: i64) -> Result<i64> {
    Ok(-value)
}

#[tokio::test]
async fn dispatch_string_round_trip() -> Result<()> {
    let registry = ToolRegistry::new().register(Arc::new(Echo.into_adapter()))?;
    let out = registry
        .dispatch(
            "call_1",
            "echo",
            json!({"message": "hi"}),
            &ExecutionContext::new(),
        )
        .await?;
    assert_eq!(out, json!("hi"));
    Ok(())
}

#[tokio::test]
async fn dispatch_typed_input_with_ctx() -> Result<()> {
    let registry = ToolRegistry::new().register(Arc::new(Add.into_adapter()))?;
    let out = registry
        .dispatch(
            "call_1",
            "add",
            json!({"a": 7, "b": 5}),
            &ExecutionContext::new(),
        )
        .await?;
    assert_eq!(out, json!(12));
    Ok(())
}

#[tokio::test]
async fn dispatch_ctxless_tool() -> Result<()> {
    let registry = ToolRegistry::new().register(Arc::new(Negate.into_adapter()))?;
    let out = registry
        .dispatch(
            "call_1",
            "negate",
            json!({"value": 9}),
            &ExecutionContext::new(),
        )
        .await?;
    assert_eq!(out, json!(-9));
    Ok(())
}

#[test]
fn metadata_uses_function_name_and_first_doc_paragraph() {
    let adapter = Echo.into_adapter();
    let meta = entelix_core::tools::Tool::metadata(&adapter);
    assert_eq!(meta.name, "echo");
    assert_eq!(meta.description, "Echo the message back verbatim.");
}

#[test]
fn metadata_carries_autogenerated_input_schema() {
    let adapter = Add.into_adapter();
    let meta = entelix_core::tools::Tool::metadata(&adapter);
    let schema = &meta.input_schema;
    assert_eq!(schema["type"], "object");
    let props = schema["properties"].as_object().unwrap();
    assert!(props.contains_key("a"));
    assert!(props.contains_key("b"));
}

// Metadata-args coverage — `name` override, `effect`, `idempotent`,
// `version`, `retry_hint`. Mirrors the calculator-style migration:
// pure-fn tool with non-default metadata. Dev-side comments use `//`
// so they don't blend into the model-facing description.
#[tool(
    name = "calc_v1",
    effect = "ReadOnly",
    idempotent,
    version = "1.0.0",
    retry_hint = "idempotent_transport"
)]
/// Square an integer.
async fn square(_ctx: &AgentContext<()>, n: i64) -> Result<i64> {
    Ok(n * n)
}

#[test]
fn metadata_args_override_defaults() {
    let adapter = Square.into_adapter();
    let meta = entelix_core::tools::Tool::metadata(&adapter);
    assert_eq!(meta.name, "calc_v1");
    assert_eq!(meta.description, "Square an integer.");
    assert!(meta.idempotent);
    assert_eq!(meta.version.as_deref(), Some("1.0.0"));
    assert!(meta.retry_hint.is_some());
    assert!(matches!(
        meta.effect,
        entelix_core::tools::ToolEffect::ReadOnly
    ));
}

#[test]
fn malformed_input_is_rejected_at_dispatch() {
    let registry = ToolRegistry::new()
        .register(Arc::new(Add.into_adapter()))
        .unwrap();
    let runtime = tokio::runtime::Runtime::new().unwrap();
    let err = runtime.block_on(async {
        registry
            .dispatch("call_1", "add", json!({"a": 1}), &ExecutionContext::new())
            .await
            .unwrap_err()
    });
    let msg = err.to_string();
    assert!(msg.contains("add"), "got: {msg}");
}
